export const INCREASE_INDEX_ACTION = 'App/INCREASE_INDEX_ACTION';
export const GET_GIF_URL_REQUEST = 'App/GET_GIF_URL_REQUEST';
export const GET_GIF_URL_RESPONSE = 'App/GET_GIF_URL_RESPONSE';
export const GET_GIF_URL_ERROR = 'App/GET_GIF_URL_ERROR';
